### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'undefined')

### ISSUE THREAD

**Issue by rpatterson** [linthtml/linthtml#507]
After following the README to install and generate a configuration I get the following inscrutable error and traceback:

```
$ ~.nvm/nvm-exec npm exec -- linthtml --init
$ ~.nvm/nvm-exec npm exec -- linthtml index.html
✖ Searching for files
TypeError: Cannot read properties of undefined (reading 'undefined')
    at print_errors (/home/rpatterson/src/nOrg/node_modules/@linthtml/linthtml/node_modules/@linthtml/cli/dist/print-errors.js:10:57)
    at lint (/home/rpatterson/src/nOrg/node_modules/@linthtml/linthtml/node_modules/@linthtml/cli/dist/index.js:100:36)
    at Object.cli [as default] (/home/rpatterson/src/nOrg/node_modules/@linthtml/linthtml/node_modules/@linthtml/cli/dist/index.js:87:12)
    at Object.<anonymous> (/home/rpatterson/src/nOrg/node_modules/@linthtml/linthtml/bin/linthtml.js:4:33)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

From `./package-lock.json`:

```
+    "node_modules/@linthtml/linthtml": {
+      "version": "0.9.4",
+      "resolved": "https://registry.npmjs.org/@linthtml/linthtml/-/linthtml-0.9.4.tgz",
+      "integrity": "sha512-xssNQnMwwb4llZxucaxSt8HzYXsM8ju+t4Doq/yrk4zbFiBCzRCfFQSE/RwP4955xpUxY9o4g5o68jsVc4iCpw==",
+      "dev": true,
+      "dependencies": {
+        "@linthtml/cli": "^0.9.3",
+        "@linthtml/dom-utils": "^0.9.0",
+        "@linthtml/html-parser": "^0.9.0",
+        "bulk-require": "1.0.1",
+        "cosmiconfig": "7.0.0",
+        "global-modules": "^2.0.0",
+        "globby": "^11.0.2",
+        "ignore": "^5.1.4",
+        "lodash.pull": "4.1.0",
+        "resolve-from": "^5.0.0",
+        "rewiremock": "^3.14.3"
+      },
+      "bin": {
+        "linthtml": "bin/linthtml.js"
+      }
+    },
```

**Comment by KamiKillertO** [comment]
@rpatterson Thanks for reporting.
What version of nodejs are you using? And can you share the HTML file "causing" the issue ?

**Comment by rpatterson** [comment]
Apologies.  At the time I had myself convinced that what I included in the description was sufficient to reproduce it, but I was wrong.  Using this script:

```
#!/bin/bash

grep -E '"version":' ~/.nvm/package.json
cd "$(mktemp -d)"
echo "18" >"./.nvmrc"
~/.nvm/nvm-exec npm install "@linthtml/linthtml"
~/.nvm/nvm-exec npm exec -- linthtml --init
~/.nvm/nvm-exec npm exec -- linthtml index.html
```

I see the following output:

```
  "version": "0.39.3",
npm WARN reify invalid or damaged lockfile detected
npm WARN reify please re-try this operation once it completes
npm WARN reify so that the damage can be corrected, or perform
npm WARN reify a fresh install with no lockfile if the problem persists.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

added 300 packages in 1s

41 packages are looking for funding
  run `npm fund` for details
Invalid option "--yes".
✔ Found 0 files
✔ Files analyzed

✨  There's no problem, good job 👏
```

I even copied what I think was the `./index.html` at the time of opening the issue in place before running `$ linthtml --init` but I still couldn't reproduce the issue.  So I can no longer reproduce this and I'm closing it until someone else runs into it and can properly document how to reproduce this issue.  Sorry for the wasted cycles!
